#include kitty-themes/themes/Catppuccin-Macchiato.conf
#include kitty-themes/themes/Kaolin_Aurora.conf
#include kitty-themes/themes/Catppuccin-Macchiato.conf
include kitty-themes/themes/Catppuccin-Mocha.conf

# Config
cursor_shape beam
cursor_beam_thickness 1.5
confirm_os_window_close 0


# URL underline color when hovering with mouse
url_color #ff3e3e
open_url_with default
detect_urls yes
copy_on_select yes
url_style curly

# Opacity
background_opacity 0.98
#background_blur 1

# The basic colors
foreground              #CDD6F4
background              #252525
selection_foreground    #9fef00
selection_background    #F5E0DC

# BEGIN_KITTY_FONTS
font_family      family="Iosevka Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

# Cursor
cursor_trail 2
cursor_trail_decay 0.1 0.4
cursor      #9fef00

# Window
remember_window_size  yes
window_border_width 0.5pt
window_margin_width 1.4
#window_logo_path /home/red/.config/kitty/kitty.png

# Tab
tab_bar_edge            bottom
tab_title_template      {index}: {title}
focus_follows_mouse     yes
active_tab_foreground   #000
active_tab_background   #9fef00
active_tab_font_style   bold
inactive_tab_foreground #444
inactive_tab_background #999
inactive_tab_font_style normal



